import typing

import jax
import jax.numpy as jnp


class NetworkState(typing.NamedTuple):
    """
    Instantaneous dynamic state of the network at a SINGLE time step k.
    All arrays have shape (N,), where N is the total number of sections.
    This is the internal state passed from one step to the next.
    """

    density: jax.Array  # rho_i(k) : Traffic density (veh/km/lane) - Shape: (N,)
    flow: jax.Array  # q_i(k)   : Traffic flow/volume (veh/h) - Shape: (N,)
    speed: jax.Array  # v_i(k)   : Mean velocity (km/h) - Shape: (N,)


class SimulationTrajectory(typing.NamedTuple):
    """
    The full simulation history over the time horizon K.
    All arrays have shape (K, N).
    This is automatically generated by jax.lax.scan stacking the NetworkStates.
    """

    density: jax.Array  # Shape: (K, N)
    flow: jax.Array  # Shape: (K, N)
    speed: jax.Array  # Shape: (K, N)


class NetworkParameters(typing.NamedTuple):
    """
    Static physical and empirical parameters for the N network sections.
    Arrays have shape (N,) to allow heterogeneous sections (e.g., lane drops).
    """

    T: float  # Simulation time step size (scalar, usually in hours)

    # Physical segment parameters
    L: jax.Array  # L_i        : Length of each section (km)
    lambda_: jax.Array  # lambda_i   : Number of lanes per section

    # Empirical METANET parameters (learnable)
    tau: jax.Array  # tau        : Relaxation time constant
    nu: jax.Array  # nu         : Anticipation sensitivity
    kappa: jax.Array  # kappa      : Density anticipation constant
    delta: jax.Array  # delta      : Merging sensitivity (on-ramps friction)
    alpha: jax.Array  # alpha      : Fundamental diagram shape parameter
    critical_density: jax.Array  # rho_cr     : Critical density (capacity threshold)
    free_flow_speed: jax.Array  # v_free     : Free flow speed


class BoundarySequence(typing.NamedTuple):
    """
    Exogenous inputs and boundaries for the ENTIRE time horizon K.
    The jax.lax.scan function will automatically slice these along the first axis
    (Time) and pass them into the step function as 1D arrays at each step.
    """

    # Boundary points over time (Shape: (K,))
    q_0: jax.Array  # q_0(1...K)     : Upstream incoming flow
    v_0: jax.Array  # v_0(1...K)     : Upstream incoming speed
    rho_N_plus_1: jax.Array  # rho_{N+1}(1...K): Downstream leaving density

    # Exogenous network inputs over time (Shape: (K, N))
    r: jax.Array  # r_i(1...K)     : On-ramp volumes per section
    s: jax.Array  # s_i(1...K)     : Off-ramp flows per section


def steady_state_speed(density: jax.Array, p: NetworkParameters) -> jax.Array:
    """Computes the equilibrium speed V(rho) based on the standard exponential fundamental diagram."""
    return p.free_flow_speed * jnp.exp(
        -(1.0 / p.alpha) * jnp.power(density / p.critical_density, p.alpha)
    )


def compute_flow(
    density: jax.Array, speed: jax.Array, p: NetworkParameters
) -> jax.Array:
    """Flow Equation (Hydrodynamic Relation)"""
    return density * speed * p.lambda_


def update_density(
    density: jax.Array,
    flow: jax.Array,
    q_upstream: jax.Array,
    r: jax.Array,
    s: jax.Array,
    p: NetworkParameters,
) -> jax.Array:
    """Density Dynamics (Conservation Law)"""
    next_density = density + (p.T / (p.L * p.lambda_)) * (q_upstream - flow + r - s)
    # Physical constraint: density cannot be negative
    return jnp.maximum(next_density, 0.0)


def update_speed(
    density: jax.Array,
    speed: jax.Array,
    v_upstream: jax.Array,
    rho_downstream: jax.Array,
    V_rho: jax.Array,
    r: jax.Array,
    p: NetworkParameters,
) -> jax.Array:
    """Empirical Momentum Equation"""
    # 1. Relaxation term
    relaxation = (p.T / p.tau) * (V_rho - speed)

    # 2. Convection term
    convection = (p.T / p.L) * speed * (v_upstream - speed)

    # 3. Anticipation term
    anticipation = (
        -(p.nu * p.T)
        / (p.tau * p.L)
        * ((rho_downstream - density) / (density + p.kappa))
    )

    # 4. Merging term
    merging = -(p.delta * p.T) / (p.L * p.lambda_) * ((r * speed) / (density + p.kappa))

    next_speed = speed + relaxation + convection + anticipation + merging

    # Physical constraint: speed cannot be negative
    return jnp.maximum(next_speed, 0.0)


def metanet_step(
    state: NetworkState, boundaries_k: BoundarySequence, p: NetworkParameters
) -> tuple[NetworkState, NetworkState]:
    """
    Advances the network state by one single time step k.
    This function isolates spatial dependencies using JAX concatenations.
    """
    # Extract instantaneous steady-state speeds
    V_rho = steady_state_speed(state.density, p)

    # --- Spatial Coupling (Array Slicing) ---
    # Convert scalar boundaries for this step into arrays of shape (1,) for concatenation
    q_0_arr = jnp.atleast_1d(boundaries_k.q_0)
    v_0_arr = jnp.atleast_1d(boundaries_k.v_0)
    rho_N_plus_1_arr = jnp.atleast_1d(boundaries_k.rho_N_plus_1)

    # Create the i-1 (upstream) and i+1 (downstream) arrays
    q_upstream = jnp.concatenate([q_0_arr, state.flow[:-1]])
    v_upstream = jnp.concatenate([v_0_arr, state.speed[:-1]])
    rho_downstream = jnp.concatenate([state.density[1:], rho_N_plus_1_arr])

    # --- State Updates ---
    next_density = update_density(
        state.density, state.flow, q_upstream, boundaries_k.r, boundaries_k.s, p
    )
    next_speed = update_speed(
        state.density, state.speed, v_upstream, rho_downstream, V_rho, boundaries_k.r, p
    )

    # Compute next flow based on the updated density and speed
    next_flow = compute_flow(next_density, next_speed, p)

    next_state = NetworkState(density=next_density, flow=next_flow, speed=next_speed)

    # For jax.lax.scan, we must return a tuple (carry, output).
    # Here, both the internal carry and the logged output are the next state.
    return next_state, next_state


@jax.jit
def rollout_simulation(
    initial_state: NetworkState, boundaries: BoundarySequence, p: NetworkParameters
) -> SimulationTrajectory:
    """
    Executes the simulation over the entire time horizon K using jax.lax.scan.
    This replaces typical Python 'for' loops with highly optimized compiled code.
    """

    # A tiny wrapper function because jax.lax.scan only accepts (carry, inputs)
    def scan_fn(carry_state, boundary_k):
        return metanet_step(carry_state, boundary_k, p)

    # Run the optimized loop
    # final_state is the NetworkState at k=K
    # trajectory_states contains the stacked NetworkStates for k=1 to K
    final_state, trajectory_states = jax.lax.scan(scan_fn, initial_state, boundaries)

    # Cast the output into our SimulationTrajectory struct
    trajectory = SimulationTrajectory(
        density=trajectory_states.density,
        flow=trajectory_states.flow,
        speed=trajectory_states.speed,
    )

    return trajectory
